name = "should-i-work"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = true

[observability]
enabled = true

[triggers]
crons = ["0 17 * * *", "0 4 * * *", "5 17 * * SUN", "0 10 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "1e1ee58b328d4f6ca80bb12ba5aae26b"
